run:
  deadline: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - wrapcheck
    - forbidigo
    # - gochecknoinits
    # - gocritic
    # - gofumpt
    # - gosec
    # - whitespace
    #- gochecknoglobals
    # - nlreturn
    # - predeclared
    # - wastedassign
    # - paralleltest
    # - exhaustivestruct
    # - unconvert
    # - godot
    - wsl
    - goerr113
    - golint
    - varnamelen
    - revive
    - scopelint
    - funlen
    - cyclop
    - maligned
    - interfacer
    - dupl
    - nolintlint
