run:
  deadline: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - wrapcheck
    - forbidigo
    - gochecknoinits
    - gocritic
    - gofumpt
    - gosec
    - whitespace
    - wsl
    - gochecknoglobals
    - goerr113
    - nlreturn
    - predeclared
    - wastedassign
    - varnamelen
    - paralleltest
    - exhaustivestruct
    # - unconvert
    # - godot
    - revive
    - golint
    - scopelint
    - funlen
    - cyclop
