run:
  deadline: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - wrapcheck
    - forbidigo
    - golint
    - varnamelen
    - revive
    - scopelint
    - funlen
    - cyclop
    - maligned
    - interfacer
    - dupl
    - nolintlint
