run:
  deadline: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - golint # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - interfacer # deprecated
    - revive # blanck import for database driver
    - funlen # func:HandleEdit
    - dupl # in test files
    - varnamelen
    - cyclop
    - nolintlint
    - forbidigo 